### PR TITLE
Raster upload

### PR DESCRIPTION
**Pull request by snowman2**
Added method for raster upload via Django file handle.

### CODE REVIEW

**Comment by sdc50** [comment]
@swainn are these able to be merged in? I don't want to mess up anything you're doing with the Python 3 update, but if we can get these move in that would be helpful on my end. I'm happy to do the merging as long as it won't throw you off.

**Comment by swainn** [comment]
@sdc50 need to talk about this during our next scrum. I meant to discuss earlier, but other things were taking precedent. Sorry for the delay, but I have some concerns that we need to discuss.

**Comment by sdc50** [comment]
@snowman2 Can you look at these two pull requests and only keep the most recent one?

**Comment by snowman2** [comment]
@sdc50, I closed the other pull request.

**Pull request closed without merging**
